export const redirectMap: Record<string, string> = {
  '/index.html': '/',
  '/about-us.html': '/about-us',
  '/spaces.html': '/spaces',
  '/gallery.html': '/gallery',
  '/faqs.html': '/faqs',
  '/contact.html': '/contact',
  '/blog.html': '/blog',
  '/about': '/about-us',
  '/contact-us': '/contact',
  // Legacy WordPress paths still indexed in Search Console
  '/home-1': '/',
  '/home-1/': '/',
  '/home': '/',
  '/home/': '/',
  '/shop': '/',
  '/shop/': '/',
  '/cyber-heights': '/levana-cyber-heights',
  '/levana': '/levana-cyber-heights',
  '/bhavya': '/bhavya-corporate-tower',
  '/bhavya-tower': '/bhavya-corporate-tower',
  '/virtual-office-gst': '/gst-registration-lucknow',
  '/virtual-office-gst-registration': '/gst-registration-lucknow',
  '/virtual-office-company-registration': '/company-registration-lucknow',
};
